provincia(buenos_aires).
provincia(caba).
provincia(entre_rios).
provincia(corrientes).
provincia(misiones).
provincia(chaco).
provincia(formosa).
provincia(jujuy).
provincia(salta).
provincia(la_rioja).
provincia(santiago_del_estero).
provincia(cordoba).
provincia(santa_fe).
provincia(san_luis).
provincia(san_juan).
provincia(mendoza).
provincia(tucuman).
provincia(la_pampa).
provincia(neuquen).
provincia(rio_negro).
provincia(chubut).
provincia(santa_cruz).
provincia(tierra_del_fuego).
linda(buenos_aires,la_pampa).
linda(buenos_aires,cordoba).
linda(buenos_aires,santa_fe).
linda(buenos_aires,entre_rios).
linda(buenos_aires,caba).
linda(caba,buenos_aires).
linda(entre_rios,buenos_aires).
linda(entre_rios,santa_fe).
linda(entre_rios,corrientes).
linda(corrientes,misiones).
linda(corrientes,entre_rios).
linda(corrientes,chaco).
linda(corrientes,santa_fe).
linda(misiones,corrientes).
linda(chaco,formosa).
linda(chaco,salta).
linda(chaco,santiago_del_estero).
linda(chaco,santa_fe).
linda(jujuy,salta).
linda(salta,formosa).
linda(salta,catamarca).
linda(la_rioja,catamarca).
linda(la_rioja,tucuman).
linda(la_rioja,santiago_del_estero).
linda(la_rioja,cordoba).
linda(la_rioja,san_juan).
linda(santiago_del_estero,tucuman).
linda(santiago_del_estero,salta).
linda(santiago_del_estero,chaco).
linda(santiago_del_estero,santa_fe).
linda(santiago_del_estero,cordoba).
linda(santiago_del_estero,catamarca).
linda(cordoba,santiago_del_estero).
linda(cordoba,catamarca).
linda(cordoba,la_rioja).
linda(cordoba,san_luis).
linda(cordoba,la_pampa).
linda(santa_fe,buenos_aires).
linda(santa_fe,entre_rios).
linda(santa_fe,corrientes).
linda(santa_fe,chaco).
linda(santa_fe,santiago_del_estero).
linda(santa_fe,cordoba).
linda(san_luis,cordoba).
linda(san_luis,la_rioja).
linda(san_luis,mendoza).
linda(san_luis,san_juan).
linda(san_juan,san_luis).
linda(san_juan,la_rioja).
linda(san_juan,mendoza).
linda(mendoza,san_juan).
linda(mendoza,san_luis).
linda(mendoza,la_pampa).
linda(mendoza,neuquen).
linda(tucuman,catamarca).
linda(la_pampa,buenos_aires).
linda(la_pampa,san_luis).
linda(la_pampa,mendoza).
linda(la_pampa,rio_negro).
linda(neuquen,mendoza).
linda(neuquen,rio_negro).
linda(rio_negro,la_pampa).
linda(rio_negro,neuquen).
linda(rio_negro,chubut).
linda(chubut,rio_negro).
linda(chubut,santa_cruz).
linda(santa_cruz,chubut).
linda(santa_cruz,tierra_del_fuego).
linda(tierra_del_fuego,santa_cruz).
size([],0).
size([_|Y], N):-N is N1+1,size(Y, N1).
siNo(X):-true\==visit(X).
visitar(Y):-true\==visit(Y),asserta(visit(Y)).
caminar(Y):-true\==camino(Y),asserta(camino(Y)).
bucle1(T):-camino(X),linda(X,Y),visitar(Y),append(T,[Y],T),bucle1(T).
recorriendo(T):-visitar(buenos_aires),visit(X),caminar(X),bucle1([]),append(T,[X],T);visit(X),caminar(X),bucle1([]),append(T,[X],T),recorriendo(T).

